#!/bin/zsh
host=mnz
rsync -av /f/svelte-todo $host:/srv/ --exclude={"node_modules/*","lucia.db","src/lib/server/db/sqlite.db",".env","build/*"} --delete
ssh $host chown -R forum:forum /srv/svelte-todo

pnpm i && pnpm run build && pnpm push:db && killall -9 node ; HOST=127.0.0.1 PORT=4001 node build
